### PR TITLE
Support using filepaths instead of stdin

### PR DESCRIPTION
**Pull request by eric-hansen**
I don't use Docker so I'm not sure how STDIN works with that, but I do use Podman and it was causing errors.

What would happen is that the container would be outputting the STDIN along with the necessary results/report.

This PR resolves 2 issues:
* Assumption that Docker is the container management solution (now Podman is usable w/o creating a symlink)
* If phpcs calls are failing, the user can instead try to pass the filename to phpcs

The default values are what was there as of current master.  I had no issues once these changes were made in seeing phpcs results and formatting the buffer, though I did not try formatting a range but only the entire buffer itself.

### CODE REVIEW

**Comment by mtbdata711** [comment]
Hey @eric-hansen,

Cheers for this!

LGTM.

Sorry about the delay, I've never used Podman before.

This all looks great to me! Podman support works as expected and there is no impact on the existing Docker version.

Now that the extension supports Podman it would be useful to update the ReadMe to include this information along with an update of the quick start for Podman users. Would you be interested in adding this in an additional PR?

Thanks again,

Matthew

**Comment by mtbdata711** [comment]
This has now been released in version 0.0.7!

**Comment by eric-hansen** [comment]
> Now that the extension supports Podman it would be useful to update the ReadMe to include this information along with an update of the quick start for Podman users. Would you be interested in adding this in an additional PR?

I updated the README in this PR with the new params, the only additional thing I can think of to add would be "this supports these container tools:" but that would just be "Docker and Docker-like (i.e.: Podman) drop-in replacements" or something.

Other than updating the appropriate settings/flags there really is no different steps needed, but if you feel the flags need more descriptiveness I can certainly update the README in another PR.

**Comment by mtbdata711** [comment]
Hey @eric-hansen!

I agree, the bulk of the changes should be limited to just updating references to Docker to Docker-like etc. I really like your phrasing for it -  "Docker and Docker-like (i.e.: Podman) drop-in replacements" - so I'd be happy to go with that.

I think it would be benefical to add some updates to the  [Docker settings ](https://github.com/mtbdata711/vscode-phpsab-docker#docker-settings) section of the ReadMe. This would inclue the additional params added for Podman use-cases.

Let me know what you think! As I said, Podman is a new tool for me and beyond my knowledge. However, I can see that users may get some use out of this extension.

Cheers

**Pull request merged**
